### ISSUE TITLE
Build on Ubuntu 16.04

### ISSUE THREAD

**Issue by stephanmg** [VRL-Studio/VRL-Studio#32]
Dear @miho,

I just cloned the repository's master branch and used ant to build VRL-Studio.

After this, I go to dist-final folder and execute the run command:

```
>> starting with no param
>> detected x86 (64 bit) os
>> using java executable from: jre/x64/bin/java
Picked up JAVA_TOOL_OPTIONS: 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: eu/mihosoft/vrl/reflection/VisualCanvas
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: eu.mihosoft.vrl.reflection.VisualCanvas
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more

```
Do you have any hints what is going wrong here? I presume it is not finding the VRL.jar dependency? But how is this possible?

Java information:
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~16.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

Best wishes,
Stephan

**Comment by miho** [comment]
Hi Stephan,

I cant reproduce this behavior on my machine. I can only assume that your VRL.jar is corrupt. Did you build VRL or are you using the official VRL release?

**Comment by stephanmg** [comment]
@miho I have built VRL from the HEAD version in the master branch.

**Comment by miho** [comment]
It still works for me with the HEAD revision. But I haven't tried it on Ubuntu. I can try it in a VM, if the problems persist.

**Comment by stephanmg** [comment]
Well, for now it is fine, as the current stable VRL-Studio from your website works for me fine. I just am interested in running most recent software in general.

So are you saying if I would clone VRL-Studio/VRL-Studio and try to build it I should be succesful? (Note that I build my own VRL.jar).

**Comment by miho** [comment]
Yes, I just confirmed that it works (macOS and Windows). I can't test Ubuntu right now.

**Comment by stephanmg** [comment]
Okay, more information from my side:

1) I build VRL.jar from the HEAD of master branch in repository VRL
2) I copy the files to the dependencies folder in the VRL-Studio Netbeans/ant project
3) I invoke ant on VRL-Studio

Then I start VRL-Studio. Maybe I cannot use the head revision of VRL repository to build the VRL.jar?

Best,
Stephan

**Comment by stephanmg** [comment]
Any chance of a progress here @miho? :)
